// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Cd0t34fOwbVCyD9XsjI_jGd8SpirALU',
    appId: '1:956024028470:web:1c3e376bf0a7c2fffc4797',
    messagingSenderId: '956024028470',
    projectId: 'brew-crew-6cda7',
    authDomain: 'brew-crew-6cda7.firebaseapp.com',
    storageBucket: 'brew-crew-6cda7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChqh_R6lfglt4KFFRNBH5Fbh5-y3vbk38',
    appId: '1:956024028470:android:d83f034ab8a56311fc4797',
    messagingSenderId: '956024028470',
    projectId: 'brew-crew-6cda7',
    storageBucket: 'brew-crew-6cda7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqvrB8Vawm-BTpP1Oig3JwqFCbf3QcYbM',
    appId: '1:956024028470:ios:139af6e719e6ec77fc4797',
    messagingSenderId: '956024028470',
    projectId: 'brew-crew-6cda7',
    storageBucket: 'brew-crew-6cda7.appspot.com',
    iosClientId: '956024028470-40171frr990lvfbvvkng5hl711pmljb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqvrB8Vawm-BTpP1Oig3JwqFCbf3QcYbM',
    appId: '1:956024028470:ios:139af6e719e6ec77fc4797',
    messagingSenderId: '956024028470',
    projectId: 'brew-crew-6cda7',
    storageBucket: 'brew-crew-6cda7.appspot.com',
    iosClientId: '956024028470-40171frr990lvfbvvkng5hl711pmljb6.apps.googleusercontent.com',
    iosBundleId: 'com.example.brewCrew',
  );
}
